### POST request to create patient
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "franz kafka",
  "email": "kafka_test_2@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

###